# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: 涼果笔记
  pageTitleSuffix: " | 涼果笔记"
  enableSPA: true
  enablePopovers: true
  analytics:
    provider: umami
    websiteId: ae900655-a5c5-4662-b01c-d938d11afad0
    host: https://umami-api.kokomi.me
  locale: zh-CN
  baseUrl: obsidian.kokomi.me
  ignorePatterns:
    - "**/.*"
    - Templates
    - "**/*.excalidraw.md"
  theme:
    fontOrigin: local
    cdnCaching: true
    typography:
      header: MiSans VF
      body: MiSans VF
      code: JetBrains Mono
    colors:
      lightMode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#4e4e4e"
        dark: "#2b2b2b"
        secondary: "#284b63"
        tertiary: "#84a59d"
        highlight: rgba(143, 159, 169, 0.15)
        textHighlight: "#fff23688"
      darkMode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b97aa"
        tertiary: "#84a59d"
        highlight: rgba(143, 159, 169, 0.15)
        textHighlight: "#b3aa0288"
plugins:
  - source: https://gh-proxy.com/github.com/quartz-community/created-modified-date
    enabled: true
    options:
      defaultDateType: modified
      priority:
        - frontmatter
        - git
        - filesystem
    order: 10
  - source: https://gh-proxy.com/github.com/quartz-community/syntax-highlighting
    enabled: true
    options:
      theme:
        light: github-light
        dark: github-dark
      keepBackground: false
    order: 20
  - source: https://gh-proxy.com/github.com/quartz-community/obsidian-flavored-markdown
    enabled: true
    options:
      comments: true
      highlight: true
      wikilinks: true
      callouts: true
      mermaid: true
      parseTags: true
      parseArrows: true
      parseBlockReferences: true
      enableInHtmlEmbed: false
      enableYouTubeEmbed: true
      enableVideoEmbed: true
      enableCheckbox: true
    order: 30
  - source: https://gh-proxy.com/github.com/quartz-community/github-flavored-markdown
    enabled: true
    order: 40
  - source: https://gh-proxy.com/github.com/quartz-community/table-of-contents
    enabled: true
    order: 50
    layout:
      position: right
      priority: 30
  - source: https://gh-proxy.com/github.com/quartz-community/crawl-links
    enabled: true
    options:
      markdownLinkResolution: shortest
      prettyLinks: false
      openLinksInNewTab: true
      # disableBrokenWikilinks 不识别文件夹页面
      # disableBrokenWikilinks: true
    order: 60
  - source: ./quartz-custom/description
    enabled: true
    order: 70
  # - source: https://gh-proxy.com/github.com/quartz-community/latex
  #   enabled: true
  #   options:
  #     renderEngine: katex
  #   order: 80
  # - source: https://gh-proxy.com/github.com/quartz-community/citations
  #   enabled: false
  #   order: 85
  - source: https://gh-proxy.com/github.com/quartz-community/hard-line-breaks
    enabled: true
    order: 90
  # - source: https://gh-proxy.com/github.com/quartz-community/ox-hugo
  #   enabled: false
  #   order: 91
  # - source: https://gh-proxy.com/github.com/quartz-community/roam
  #   enabled: false
  #   order: 92
  - source: https://gh-proxy.com/github.com/quartz-community/remove-draft
    enabled: true
  # - source: https://gh-proxy.com/github.com/quartz-community/explicit-publish
  #   enabled: false
  - source: https://gh-proxy.com/github.com/quartz-community/alias-redirects
    enabled: true
  - source: https://gh-proxy.com/github.com/quartz-community/content-index
    enabled: true
    options:
      enableSiteMap: true
      enableRSS: true
  - source: https://gh-proxy.com/github.com/quartz-community/favicon
    enabled: true
  - source: https://gh-proxy.com/github.com/quartz-community/og-image
    enabled: true
    order: 70
  - source: https://gh-proxy.com/github.com/quartz-community/cname
    enabled: true
  - source: https://gh-proxy.com/github.com/quartz-community/canvas-page
    enabled: true
  - source: https://gh-proxy.com/github.com/quartz-community/content-page
    enabled: true
  - source: https://gh-proxy.com/github.com/quartz-community/folder-page
    enabled: true
  - source: https://gh-proxy.com/github.com/quartz-community/tag-page
    enabled: true
  - source: https://gh-proxy.com/github.com/quartz-community/explorer
    enabled: true
    layout:
      position: left
      priority: 50
  - source: https://gh-proxy.com/github.com/enihsyou/quartz-community-graph
    enabled: true
    layout:
      position: right
      priority: 10
  - source: https://gh-proxy.com/github.com/quartz-community/search
    enabled: true
    layout:
      position: left
      priority: 20
      group: toolbar
      groupOptions:
        grow: true
  - source: https://gh-proxy.com/github.com/quartz-community/backlinks
    enabled: true
    layout:
      position: right
      priority: 30
  - source: https://gh-proxy.com/github.com/quartz-community/article-title
    enabled: true
    layout:
      position: beforeBody
      priority: 10
  - source: ./quartz-custom/content-meta
    enabled: true
    options:
      repoBlobLink: "https://github.com/enihsyou/Obsidian-Vault/blob/enihsyou-PC"
    layout:
      position: beforeBody
      priority: 20
  - source: https://gh-proxy.com/github.com/quartz-community/tag-list
    enabled: true
    layout:
      position: beforeBody
      priority: 30
  - source: https://gh-proxy.com/github.com/quartz-community/page-title
    enabled: true
    layout:
      position: left
      priority: 10
  - source: https://gh-proxy.com/github.com/quartz-community/darkmode
    enabled: true
    layout:
      position: left
      priority: 30
      group: toolbar
  - source: https://gh-proxy.com/github.com/quartz-community/reader-mode
    enabled: true
    layout:
      position: left
      priority: 35
      group: toolbar
  - source: https://gh-proxy.com/github.com/quartz-community/breadcrumbs
    enabled: true
    layout:
      position: beforeBody
      priority: 5
      condition: not-index
  - source: https://gh-proxy.com/github.com/quartz-community/comments
    enabled: true
    options:
      provider: giscus
      options:
        repo: enihsyou/Obsidian-Vault
        repoId: R_kgDOPfEx_Q
        category: Post Comments
        categoryId: DIC_kwDOPfEx_c4CwvbC
        lang: zh-CN
        mapping: title
        strict: true
        reactionsEnabled: true
        inputPosition: bottom
    layout:
      position: afterBody
      priority: 20
      condition: content-comments
  - source: https://gh-proxy.com/github.com/quartz-community/footer
    enabled: true
    options:
      links:
        GitHub: https://github.com/enihsyou/Obsidian-Vault/tree/pages
        Blog: https://blog.kokomi.me
  - source: ./quartz-custom/recent-notes
    enabled: true
    options:
      limit: 3
      showTags: true
      hideTagPages: true
      hideFolderPages: true
      linkToHistory: "https://github.com/enihsyou/Obsidian-Vault/commits/enihsyou-PC?author=enihsyou"
    layout:
      position: afterBody
      priority: 10
      condition: index-only
  - source: https://gh-proxy.com/github.com/quartz-community/spacer
    enabled: true
    options: {}
    order: 25
    layout:
      position: left
      priority: 25
      display: mobile-only
  - source: https://gh-proxy.com/github.com/quartz-community/bases-page
    enabled: true
    options: {}
    order: 50
  - source: https://gh-proxy.com/github.com/quartz-community/note-properties
    enabled: true
    options:
      includeAll: false
      includedProperties:
        - description
        - tags
        - aliases
      excludedProperties: []
      hidePropertiesView: true
      delimiters: ---
      language: yaml
    order: 5
    layout:
      position: beforeBody
      priority: 15
      display: all
  - source: https://gh-proxy.com/github.com/quartz-community/unlisted-pages
    enabled: true
    options: {}
    order: 45
  - source: https://gh-proxy.com/github.com/quartz-community/encrypted-pages
    enabled: true
    options:
      iterations: 600000
      passwordField: password
      unlistWhenEncrypted: false
      outputPath: static/encryptedContentIndex.json
    order: 900
    layout:
      position: body
      priority: 100
      display: all
  # - source: https://gh-proxy.com/github.com/quartz-community/stacked-pages
  #   enabled: false
  #   layout:
  #     position: afterBody
  #     priority: 50
  #     display: all
  - source: ./quartz-custom/frontmatter-adapter
    enabled: true
    order: 5
    options:
      keyMappings:
        - { from: "创建时间", to: created }
        - { from: "修改时间", to: modified }
      arrayMappings:
        - { from: "相关链接", to: relavents }
  - source: ./quartz-custom/font-loader
    enabled: true
    order: 6
    options:
      stylesheets:
        - href: "https://cdn-font.hyperos.mi.com/font/css?family=MiSans_VF:VF:Chinese_Simplify,Latin&display=swap"
          crossorigin: anonymous
        - href: "https://cdn-font.hyperos.mi.com/font/css?family=Misans_TC_VF:VF:Chinese_Traditional_TW&display=swap"
          crossorigin: anonymous
        - href: "https://fontsapi.zeoseven.com/521/main/result.css"
          crossorigin: anonymous
        - href: "https://fontsapi.zeoseven.com/521/bold/result.css"
          crossorigin: anonymous
  - source: ./quartz-custom/ping
    enabled: true
  - source: ./quartz-custom/relavent-links
    enabled: true
    layout:
      position: beforeBody
      priority: 35
  - source: ./quartz-custom/floating-buttons
    enabled: true
    layout:
      position: right
      priority: 40
layout:
  groups:
    toolbar:
      priority: 35
      direction: row
      gap: 1rem
  byPageType:
    "404":
      positions:
        beforeBody: []
        left: []
        right: []
    content: {}
    folder:
      exclude:
        - reader-mode
      positions:
        right: []
    tag:
      exclude:
        - reader-mode
      positions:
        right: []
    canvas: {}
    bases: {}
