version: "3"
tasks:
  docker-preview:
    desc: 本地开发阶段使用 Docker 预览网站
    cmds:
      - docker run --rm -it -p 3000:3000 -p 3001:3001
        -v ./content:/usr/src/app/content
        -v ./quartz:/usr/src/app/quartz
        -v ./quartz.config.yaml:/usr/src/app/quartz.config.yaml:ro
        -v ./:/usr/src/app/hostdir
        -e NPM_CONFIG_UPDATE_NOTIFIER=false
        -e NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
        ghcr.nju.edu.cn/ghcr.io/jackyzha0/quartz:v5
        npx quartz build --serve --port=3000 --concurrency=4

  source-build:
    desc: 从源码目录构建网站
    preconditions:
      - sh: test -d node_modules
        msg: "please run 'pnpm install' first."
    deps:
      - fetch-content
    cmds:
      - pnpm run quartz plugin install
      - pnpm run quartz build --verbose

  fetch-content:
    desc: 从 Obsidian Vault 同步内容
    cmds:
      - git remote set-branches --add origin enihsyou-PC
      - git fetch origin enihsyou-PC
      - git worktree remove content --force || true
      - git branch -D content || true
      - git worktree add -b content ./content enihsyou-PC
  upstream-subtree-split:
    desc: 首次从上游仓库拆分 quartz 目录为独立分支
    summary: |
      只需执行一次，关于如何操作请参考
      https://obsidian.kokomi.me/Obsidian/Publish-Obsidian-Vault
    platforms:
      - windows
    cmds:
      - wsl --cd /home/enihsyou/GitHub --
        git clone https://github.com/jackyzha0/quartz.git quartz.git
      - wsl --cd /home/enihsyou/GitHub/quartz.git --
        git subtree split --prefix=quartz --branch v5-split
      - git subtree add --prefix=quartz '//wsl.localhost/Ubuntu/home/enihsyou/GitHub/quartz.git' v5-split --squash

  upstream-subtree-pull:
    desc: 从 Quartz 官方仓库拉取最新更新
    summary: |
      这个操作依赖本地有一个 quartz 仓库的 subtree
    platforms:
      - windows
    cmds:
      - |
        wsl --cd /home/enihsyou/GitHub/quartz.git -- << EOF
        git pull
        git subtree split --prefix=quartz --branch v5-split
        EOF
      - git subtree pull --prefix=quartz '//wsl.localhost/Ubuntu/home/enihsyou/GitHub/quartz.git' v5-split --squash

  clean-dist:
    desc: 清理构建产物
    cmds:
      - rm -rfv dist
      - rm -rfv public
      - rm -rfv .quartz
      - rm -rfv quartz-custom/**/dist
      - rm -rfv quartz-custom/**/package-lock.json
      - rm -rfv quartz-custom/**/node_modules
      - rm -rfv quartz/.quartz-cache